version: '3'
services:
  web:
    build: .
    ports:
      - "11616:11616"
      - "11617:11617"
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
      - REDIS_HOST_IP=${REDIS_HOST_IP}
      - ETCD_HOST_IP=${ETCD_HOST_IP}
      - SERVICE_NAME=PaymentService
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
      - "redis.digitalfunk.io:${REDIS_HOST_IP}"   