version: '3'

services:
  web:
    image: paymentservice_web
    ports:
      - "11616:11616"
      - "11617:11617"
    networks:
      - back-tier
    volumes:
      - /code
    environment:
      - HOST_IP=${HOST_IP}
      - REDIS_HOST_IP=${REDIS_HOST_IP}
      - DISCOVERY_HOST_IP=${DISCOVERY_HOST_IP}
      - ETCD_HOST_IP=${ETCD_HOST_IP}
      - SERVICE_NAME=PaymentService
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
      - INTERLOCK_DATA={"hostname":"payment", "domain":"digitalfunk.io"}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
      - "redis.digitalfunk.io:${REDIS_HOST_IP}"
      - "discovery.digitalfunk.io:${DISCOVERY_HOST_IP}" 
networks:
    back-tier:
        external: true