version: '2'
services:
  web:
    build: .
    ports:
      - "11616:11616"
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
